### PR TITLE
Instagram new api

### PR DESCRIPTION
**Pull request by jannejava**
A quick fix of the properties introduced in Instagram's new API. The changes are not tested, but I needed a quick fix and you maybe find this to some help.

### CODE REVIEW

**Comment by pgrimaud** [comment]
Thanks, I'm gonna take a lot at your PR and release a new version in minutes

**Comment by pgrimaud** [comment]
@jannejava I can't find how to paginate the feed. Any idea ?

**Comment by jannejava** [comment]
Not looking good...https://stackoverflow.com/questions/49298252/how-to-pagination-in-instagram-public-api-a-1

**Comment by pgrimaud** [comment]
Same for me, that's why I release this package

But end_cursor seems to work still on tags : https://www.instagram.com/explore/tags/space/?__a=1&max_id=AQA6xcax1Of8qjYhYiW8LQVhtp6dwFWI6dZc6ry4JiPnCWMhx7SOYk31aUlfNu36Zh6qjjqOH2JNxGRTbMu3aY22BCTZW5cmV_5S2v73VCXBPQ

**Pull request merged**
