### PR TITLE
fetching new format data to mediaDetailed

### LINKED ISSUE #268: Response for media query is changed - throws Undefined property: stdClass::$graphql
**Version(s) affected**: 6.*

**Description**  
The response for detailed media query changed and doesn't return a grapql property anymore, those affecting both getMediaDetailedByShortCode() and getMediaDetailed() methods.

**How to reproduce**  
Running any of these 2 examples:
https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/media-detailed-by-shortcode.php
https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/media-detailed.php

Screenshot 2022-02-05 at 20-47-09 🧨 Undefined property stdClass $graphql

Screenshot 2022-02-05 at 20 37 09

### PR DESCRIPTION
**Pull request by Afonin**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| Issue?        | Fix #268

### CODE REVIEW

**Comment by eldark** [comment]
I tested this, and works perfect!

**Comment by Afonin** [comment]
@pgrimaud can u check this PR please

**Comment by pgrimaud** [comment]
Thank you!

**Comment by pgrimaud** [comment]
@all-contributors please add @Afonin for code

**Pull request merged**
