### PR TITLE
fix csrf_token issue while logging in with credentials due to DOM cha…

### PR DESCRIPTION
**Pull request by sportakal**
…nges on instagram.com

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| Issue?        | Fix #csrf_token issue while logging in with credentials due to DOM changes on instagram.com

### CODE REVIEW

**Comment by alejandro** [comment]
@sportakal +1 this fixed the issues that I was having with "Unable to extract JSON data" from the Login function.

**Comment by pgrimaud** [comment]
Thank you so much @sportakal 

I totally missed your PR due to a lot of work...

**Comment by pgrimaud** [comment]
@all-contributors please add @sportakal for code

**Comment by fmchan** [comment]
now the error "Unable to extract JSON data" comes up again

**Pull request merged**
