### PR TITLE
add shortcode to media and get media by shortcode

### PR DESCRIPTION
**Pull request by David-Kurniawan**

### CODE REVIEW

**Comment by pgrimaud** [comment]
Thanks @David-Kurniawan 🎉

**Comment by David-Kurniawan** [comment]
> Thanks @David-Kurniawan tada

Your welcome
may i can join as contributor :)

**Comment by pgrimaud** [comment]
Oh sorry, I forgot 🐊

**Comment by pgrimaud** [comment]
@all-contributors please add @David-Kurniawan for code

**Pull request merged**
